/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Attribute } from "./components/gg-inline-input/gg-inline-input";
export namespace Components {
    interface GgInlineInput {
        "isEditing": boolean;
        "item": Attribute;
    }
}
declare global {
    interface HTMLGgInlineInputElement extends Components.GgInlineInput, HTMLStencilElement {
    }
    var HTMLGgInlineInputElement: {
        prototype: HTMLGgInlineInputElement;
        new (): HTMLGgInlineInputElement;
    };
    interface HTMLElementTagNameMap {
        "gg-inline-input": HTMLGgInlineInputElement;
    }
}
declare namespace LocalJSX {
    interface GgInlineInput {
        "isEditing"?: boolean;
        "item"?: Attribute;
        "onSubmitAttribute"?: (event: CustomEvent<Attribute>) => void;
    }
    interface IntrinsicElements {
        "gg-inline-input": GgInlineInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gg-inline-input": LocalJSX.GgInlineInput & JSXBase.HTMLAttributes<HTMLGgInlineInputElement>;
        }
    }
}
